#!/usr/bin/sh

#--preload-file assets \
#-s USE_SDL_IMAGE=2 \

emcc \
	src/*.cpp \
	src/ui/*.cpp \
	-s USE_SDL=2 \
	-s USE_SDL_GFX=2 \
    -s USE_SDL_TTF=2 \
	-s SDL2_IMAGE_FORMATS='["png"]' \
	-std=c++20 \
	-Isrc \
	-o "www/htpc.html"
